# source database URL
# database URLs take the format of:
#   postgres://user:password@host:port/dbname
# we recommend a command which outputs a database URL
# so sensitive information is not included in this file
from: postgres://localhost:5432/autoclearance_development

# destination database URL

to: $(echo $DATABASE_URL)
to_safe: true

# define groups
groups:
  all:
  - anon_rap_sheets
  - anon_cycles
  - anon_events
  - anon_counts
  - anon_dispositions
  - rap_sheet_properties
  - event_properties
  - count_properties
  - eligibility_estimates

# exclude tables
exclude:
- schema_migrations
- ar_internal_metadata
