inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'bin/*'

Rails:
  Enabled: true

Rails/NotNullColumn:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Metrics/BlockLength:
  Exclude:
  - 'spec/**/*'

Naming/PredicateName:
  NamePrefix: ['is_']
