inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'

Rails:
  Enabled: true

Rails/NotNullColumn:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
