version: 2
jobs:
  build:
    working_directory: ~/autoclearance

    # Primary container image where all commands run

    docker:
    - image: circleci/ruby:2.5.1-node-browsers
      environment:
        RAILS_ENV: test
        PGHOST: 127.0.0.1
        PGUSER: root

    # Service container image available at `host: localhost`

    - image: circleci/postgres:9.6.10-alpine
      environment:
        POSTGRES_USER: root
        POSTGRES_DB: circle-test_test

    steps:
    - checkout

    # Restore bundle cache
    - restore_cache:
        keys:
        - autoclearance-{{ checksum "Gemfile.lock" }}
        - autoclearance-

    # Bundle install dependencies
    - run:
        name: Install dependencies
        command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3

    - run: sudo apt install -y postgresql-client pdftk qt5-default libqt5webkit5-dev || true

    # Store bundle cache
    - save_cache:
        key: autoclearance-{{ checksum "Gemfile.lock" }}
        paths:
        - vendor/bundle

    - run:
        name: Database Setup
        command: |
          bundle exec rake db:create
          bundle exec rake db:schema:load

    - run:
        name: Run rake
        command: bin/rake

    # Save artifacts
    - store_test_results:
        path: /tmp/test-results
